### ISSUE TITLE
Using with std::format fails with gcc/libstdc++

### ISSUE THREAD

**Issue by MoshiKoi** [Neargye/magic_enum#397]
I'm trying to use magic_enum with the standard library format instead of fmt, but am running into issues when compiling with gcc/libstdc++

Simple example: https://godbolt.org/z/1onnTr7js

```cpp
#include <magic_enum/magic_enum_format.hpp>

#include <format>

enum class Foo {
  X,
};

int main() { auto result = std::format("{}", Foo::X); }
```

It throws a bunch of template errors, but the main thing seems to be that it doesn't actually define std::formatter properly. The same code works with the Microsoft STL (tested with both msvc and clang).

**Comment by Neargye** [comment]
Hi,
please test branch https://github.com/Neargye/magic_enum/pull/382, should fix this

**Comment by MoshiKoi** [comment]
That unfortunately doesn't fix it, but I actually found out the issue - it turns out `magic_enum_format.hpp` doesn't include `<format>`. Reordering the includes fixes the issue, though `magic_enum_format.hpp` should probably include it so we don't rely on include order.

**Comment by Neargye** [comment]
Fix in master.
