### ISSUE TITLE
ROS2 Kilted Sync (2025-07-28) ~ 0.9.7-1 : Fails to resolve is_nothrow_invocable_v in magic_enum::detail

### ISSUE THREAD

**Issue by jacstofberg** [Neargye/magic_enum#420]
Good day,

After the ROS2 Kilted Patch Release 1 sync, our build fails with the following error. This only happens when using the Magic Enum library released with Kilted. If we clone the same version of the Magic Enum library (0.9.7) and build from source, there are no issues.

```
In file included from /opt/ros/kilted/include/magic_enum/magic_enum_iostream.hpp:36,
                 from /myFile.cpp:21:
/opt/ros/kilted/include/magic_enum/magic_enum_flags.hpp:134:123: error: ‘is_nothrow_invocable_v’ is not a member of ‘magic_enum::detail’; did you mean ‘is_nothrow_invocable’?
  134 | [[nodiscard]] constexpr auto enum_flags_cast(string_view value, [[maybe_unused]] BinaryPredicate p = {}) noexcept(detail::is_nothrow_invocable_v<BinaryPredicate>) -> detail::enable_if_t<E, optional<std::decay_t<E>>, BinaryPredicate> {
```

This one has us scratching our heads. It seems like the library released with Kilted should work.

Thanks in advance.

**Comment by bijoua29** [comment]
I'm seeing this too. The library seems like it should work but looks like a namespace issue is causing it to fail.

**Comment by ZXShady** [comment]
Hi what version is magic enum? you can check using the version macro

**Comment by jacstofberg** [comment]
Hi,

Version 0.9.7, according to the header (magic_enum.hpp) and the [Kilted Sync 2025-07-28](https://discourse.openrobotics.org/t/new-packages-and-patch-release-for-kilted-kaiju-2025-07-28/49312).

I am not familiar with the version macro, so checked the header and Kilted packages update instead.

Thanks!

**Comment by ZXShady** [comment]
> Hi,
> 
> Version 0.9.7, according to the header (magic_enum.hpp) and the [Kilted Sync 2025-07-28](https://discourse.openrobotics.org/t/new-packages-and-patch-release-for-kilted-kaiju-2025-07-28/49312).
> 
> I am not familiar with the version macro, so checked the header and Kilted packages update instead.
> 
> Thanks!

and it worked? that's good.

**Comment by jacstofberg** [comment]
No, as per the issue description, version 0.9.7 of the library packaged with Kilted did not work. Were there any updates since the issue was raised?

**Comment by ZXShady** [comment]
> No, as per the issue description, version 0.9.7 of the library packaged with Kilted did not work. Were there any updates since the issue was raised?

I will see this tommotow is is tthis the correct repo to download from?

https://github.com/ros2-gbp/magic_enum-release/tags

Also if possible can you `magic_enum::detail::is_nothrow_invocable_v<int(*)()>` yourself and see whether that compiles?

**Comment by jacstofberg** [comment]
As per the issue description: "If we clone the same version of the Magic Enum library (0.9.7) and build from source, there are no issues."

The issue manifests specifically on the `ros-kilted-magic-enum` library (version 0.9.7-1) that was released for ROS Kilted Kaiju and available via APT (i.e. when we install the library via APT it does not work; when we build magic enum from source, it works). Not sure if the library that was released to the Kilted APT repository is somehow flawed, or whether there's some namespace resolution conflict with other dependencies released with Kilted.

**Comment by jacstofberg** [comment]
> > No, as per the issue description, version 0.9.7 of the library packaged with Kilted did not work. Were there any updates since the issue was raised?
> 
> I will see this tommotow is is tthis the correct repo to download from?
> 
> https://github.com/ros2-gbp/magic_enum-release/tags
> 
> Also if possible can you `magic_enum::detail::is_nothrow_invocable_v<int(*)()>` yourself and see whether that compiles?

Sorry about the late reply. Yes, that does seem to be the correct repo.

I just downloaded "[release/kilted/magic_enum/0.9.7-1](https://github.com/ros2-gbp/magic_enum-release/releases/tag/release%2Fkilted%2Fmagic_enum%2F0.9.7-1)" source from there and our build failed with the same error provided in the issue description.

If I download the source code for the 0.9.7 release tag from [Neargye/magic_enum](https://github.com/Neargye/magic_enum/releases/tag/v0.9.7), it builds fine. 

I compared the source from the Neargye and ROS Kilted releases of 0.9.7 and they look very different:

magic_enum_flags.hpp (at the culprit line)
---

<img width="1912" height="161" alt="Image" src="https://github.com/user-attachments/assets/b2d18678-2125-49fa-9ed4-3a148b06e8c1" />

magic_enum.hpp (note that both headers indicate version 0.9.7)
---

<img width="1916" height="608" alt="Image" src="https://github.com/user-attachments/assets/6bb74b36-6de4-4333-886e-dbcf8e1d1876" />

<img width="1916" height="608" alt="Image" src="https://github.com/user-attachments/assets/e477b429-8f41-4004-a273-032afbf51776" />

I would have expected the ROS Kilted release of magic_enum version 0.9.7 to be identical to the tagged release on Neargye. It seems the ROS Kilted release is from some subsequent commit.


Thanks!

**Comment by bijoua29** [comment]
I'll will say I don't have any knowledge of the ros2 package release process  but I think the issue might be the following:

in the following line:
https://github.com/ros2-gbp/magic_enum-release/blob/73be23da890a271689b8350bab1d9d69e4564029/tracks.yaml#L126

it should probably be
```
last_release: v0.9.7
```

and in this line:
https://github.com/ros2-gbp/magic_enum-release/blob/73be23da890a271689b8350bab1d9d69e4564029/tracks.yaml#L132

it should be
```
release_tag: v:{version}
```

With the current state of this file, it is always going to pick latest commit on 'master'. Also the above changes need to be made for other distros as well.

**Comment by Neargye** [comment]
I am not familiar with the ROS2 build process and do not maintain it, so my understanding of this issue is limited. Is there any way I can assist with this problem?

**Comment by bijoua29** [comment]
@Neargye Apparently the team that is responsible for release of magic_enum in ros2 is https://github.com/ros2-gbp/ros2-gbp-github-org/blob/e2466f71911d6af615f6347b0adfa2f71ed846fc/nobleo.tf. I think the team includes https://github.com/Rayman and https://github.com/Timple. Maybe you can add yourself to this team or contact these users to update the release versions.

**Comment by Timple** [comment]
Good day!
I've never seen this issue before and now stumbled across it by coincidence.

Is this still an issue? If so, I can probably help.

**Comment by Neargye** [comment]
Hi @Timple, this is still an issue; I would be grateful if you could help.

**Comment by Timple** [comment]
Ok, some explanation to the process.

The deployment tool (bloom) looks on the release branch (master) for the last tag and uses that tag. So the source in the gbp repo should be identical to last tag of the repo.
I'll check why this is not the case.

**Comment by Timple** [comment]
As you guys succesfully assumed: there was a mis-configuration where the last master was picked instead of the tag.

I've fixed the configuration and released version 0.9.8 to fix this.

This branch is now equal to tag v0.9.8: https://github.com/ros2-gbp/magic_enum-release/tree/release/kilted/magic_enum
Should be in the next Kilted sync. I will continue to update the other releases.

**Comment by Timple** [comment]
```
$ diff /opt/ros/kilted/include/magic_enum/ ~/repos/magic_enum/include/magic_enum/
```

```
$ grep version /opt/ros/kilted/include/magic_enum/magic_enum.hpp 
//               |___/  version 0.9.8
#  pragma clang diagnostic ignored "-Wenum-constexpr-conversion"
// This version is much lighter on the compile times and is not restricted to the enum_range limitation.
```

No diff left. Assuming this issue is fixed then.

**Comment by bijoua29** [comment]
Still getting this issue on rolling which is using version 0.9.8. Presumably will be the same on Kilted.

/opt/ros/rolling/include/magic_enum/magic_enum_flags.hpp:109:172: error: ‘is_nothrow_invocable_v’ is not a member of ‘magic_enum::detail’; did you mean ‘is_nothrow_invocable’?
  109 | [[nodiscard]] constexpr auto enum_flags_cast(string_view value, [[maybe_unused]] char_type sep = char_type{'|'}, [[maybe_unused]] BinaryPredicate p = {}) noexcept(detail::is_nothrow_invocable_v<BinaryPredicate>) -> detail::enable_if_t<E, optional<std::decay_t<E>>, BinaryPredicate> {

Works fine if you source compile 0.9.7.

**Comment by Timple** [comment]
Can you give the diff between the apt version and the source version?
Something like:
```
diff /opt/ros/rolling/include/magic_enum/ ~/repos/magic_enum/include/magic_enum/
```
